apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mysql-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: mysql
  type: {{ .Values.mysql.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.mysql.service.port }}
      targetPort: {{ .Values.mysql.service.targetPort }}
      {{- if eq .Values.mysql.service.type "NodePort" }}
      nodePort: {{ .Values.mysql.service.nodePort }}
      {{- end }}
