java:
  image:
    repository: techiescamp/kube-petclinic-app
    tag: "1.0.0"
    pullPolicy: IfNotPresent
  replicaCount: 3
  service:
    type: NodePort
    port: 8080
    targetPort: 8080
    nodePort: 30444
  url: jdbc:mysql://mysql-service.default.svc.cluster.local:3306/petclinic
  username: crunchops
  password: crunchOps@1234


