java:
  image:
    repository: 814200988517.dkr.ecr.us-west-2.amazonaws.com/java-app
    tag: "4.0.0"
    pullPolicy: IfNotPresent
  replicaCount: 2
  service:
    type: NodePort
    port: 8080
    targetPort: 8080
    nodePort: 30144
  url: jdbc:mysql://mysql-service.default.svc.cluster.local:3306/petclinic
  username: crunchops
  password: crunchOps@1234


